### ISSUE TITLE
So you deleted my issue for a Critical Bug that was found??? 5-stars for worst support ever....

### ISSUE THREAD

**Issue by Etanarvazac** [Stardust-Labs-MC/Incendium#11]
A while back I reported a bug found in XCraft Survival server where we were able to move NPC's and bypass PvP protection using certain custom items in Incendium. They were the Holy Wrath and Sentry's Wrath crossbows. And instead of helping to resolve the issue, you straight up delete the issue to hide the flaw??? Talk about earning a nomination for being the Worst Support Team of the Year Award.

**Comment by catter1** [comment]
Hello, thanks for your posting. First of all, I can assure you that we have never deleted your issue. If you look at the [issues](https://github.com/Stardust-Labs-MC/Incendium/issues) page, you will see that there are 9 open and 2 closed, adding up to 11 total. Since this issue is #11, there are no deleted issues.

I scanned our Discord, and although I do not know what your Discord account is, I could not find anyone that appeared to be you that mentioned the issue. Yes, this issue has been brought up to our attention before. My response to that has always been something along the lines of:
> datapacks cannot check for worldguard regions, and therefore not something we can really control. If you disable firework damage, arrow damage, and fire, that should help.

Now, instead of berating us for not having solved your issue, it would be more helpful for everyone involved if you just create a normal issue here in the repository. As I said before, there's not too much we can do by default about this specific one, but I am more than happy to attempt to discover more creative solutions. Next time, be more polite, please.

**Comment by catter1** [comment]
I've left this open long enough - time to close it.
