### ISSUE TITLE
Massive performance drop in the Infernal dunes biome

### ISSUE THREAD

**Issue by jaggertp** [Stardust-Labs-MC/Incendium#16]
Tested both on single player, multiplayer, and on different world, consistent frame drops from 100 frames to 1–2 frames after entering the Infernal dunes' biome. Also tried lowering render distance and disabling shader to see if it was an issue from that, but to no avail.

**Comment by catter1** [comment]
Disabling some of your particles should help with that - specifically `minecraft:falling_dust` if you have a mod that allows disablin of special ones.

Otherwise, unless there's another source of lag that I am not yet aware of in Infernal Dunes, that's the best we can do until our 1.20 Incendium update.

**Comment by NolanHewitt** [comment]
I encounter this but in ash barrens instead. It also occurs in basalt deltas though so I don't think its this mod. Not sure what would be causing this.
