### ISSUE TITLE
Compatibility with aother Nether mods

### ISSUE THREAD

**Issue by Feliks-WR** [Stardust-Labs-MC/Incendium#56]
### Describe your enhancement/improvement, with context and reasoning.

It would be awesome if this could be used alongside Better Nether, Cinderscapes, and Amplified Nether!

**Comment by sleepy-evelyn** [comment]
I mean it works fine with Cinderscapes at least 🤷‍♀️

**Comment by catter1** [comment]
- Better Nether: it's not perfect, but I believe it does work
- Cinderscapes: needs some editing, but they have a guide on how to make it more compatible
- Amplified Nether: there is zero need for it to work with it, because Incendium *IS* Amplified Nether, but with extra stuff. It just doesn't reach quite as tall as it.

Compatibility with the former two might actually improve in the future when a certain mod gets released, but otherwise, it is what it is.
