### ISSUE TITLE
[Enhancement] Is there a way to control what mobs spawn?

### ISSUE THREAD

**Issue by Tanjiraaaaa** [Stardust-Labs-MC/Incendium#86]
### Describe your enhancement/improvement, with context and reasoning.

I would like to be able to control what modded mobs spawn, like making the restless spirits not spawn. Because it slows down some of my farms in the nether by a lot.

**Comment by catter1** [comment]
There is currently no way to easily control that. If you know what you're doing, you can edit the datapack to do so, but there's not a clean way to do so. Below I've highlighted the three sets of lines to delete, but that's probably the best you can do for now. Otherwise this is unsupported.

https://github.com/Stardust-Labs-MC/Incendium/blob/1.20/data/incendium/functions/entity/mob/init.mcfunction#L25-L27
https://github.com/Stardust-Labs-MC/Incendium/blob/1.20/data/incendium/functions/entity/mob/init.mcfunction#L25-L27
https://github.com/Stardust-Labs-MC/Incendium/blob/1.20/data/incendium/worldgen/biome/weeping_valley.json#L95-L100
