### ISSUE TITLE
[Enhancement] Migration Tool

### ISSUE THREAD

**Issue by Anvil5465** [Stardust-Labs-MC/Incendium#94]
### Describe your enhancement/improvement, with context and reasoning.

When the rewrite is released, will a tool be provided to migrate from the old version of Incendium to the new one? Or will I need to start from scratch?

**Comment by catter1** [comment]
We will likely not support full migration, due to how much is changing and the amount of work it would be to make such a tool. This is why the Incendium port is not publically released for 1.21 - to discourage people from using it on new worlds, which will reduce the people wanting to upgrade from it when the rewrite rolls around.

Resetting the nether will very likely be necessary. We might not provide a special tool, but we will likely have instructions for "replacing" old items with new ones.

Please keep in mind me heavy use of "likely" and "probably". I am simply stating where our planning is at. We're a long ways out, and this can still change in any direction.
